version: '3.8'

services:
  minio:
    image: minio/minio:latest
    container_name: minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
      MINIO_ACCESS_KEY: z3pUX4l6KWmHjA3VsRrv
      MINIO_SECRET_KEY: hq5HBUuLbAfjiwl1Z8iF797ahXO3WVlGpRBpNb0g
      MINIO_REGION: kz-ala-dev
      MINIO_BROWSER: on
    ports:
      - "9000:9000"
      - "9001:9001"  # Для доступа к консоли управления MinIO
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    networks:
      local-network:
volumes:
  minio_data:
networks:
  local-network:
    external: true